language: python

sudo: false


matrix:
  include:
    - python: '3.4'
      env: ORANGE="3.5.0"

    - python: '3.6'
      env: ORANGE="release"

    - python: '3.6'
      env: ORANGE="master"

cache:
    apt: true
    pip: true

addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev
            - gfortran

install:
    # Update pip to be able to install wheel dependencies
    - pip install -U pip wheel
    - source $TRAVIS_BUILD_DIR/.travis/install_orange.sh
    - pip install -e .

script: python setup.py test
