language: python

sudo: false


matrix:
  include:
    - python: '3.5'
      env: ORANGE="3.16.0"

    - python: '3.6'
      env: ORANGE="release"

    - python: '3.6'
      env: ORANGE="master"

cache:
    apt: true
    pip: true

addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev
            - gfortran

install:
    # Update pip to be able to install wheel dependencies
    - pip install -U pip wheel
    - pip install sip pyqt5  # needs python 3.5+
    - source $TRAVIS_BUILD_DIR/.travis/install_orange.sh
    - pip install -e .

script:
    - export XVFBARGS="-screen 0 1280x1024x24"
    - catchsegv xvfb-run -a -s "$XVFBARGS" python setup.py test
